basePath: /
definitions:
  api.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  api.loginResponse:
    properties:
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API backend en Go para manejo de usuarios y autenticación JWT
  title: Task Management API
  version: "1.0"
paths:
  /api/user/change-password:
    post:
      description: Cambia la contraseña del usuario (simulado)
      responses:
        "200":
          description: Contraseña cambiada
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Cambio de contraseña
      tags:
      - user
  /api/user/login:
    post:
      consumes:
      - application/json
      description: Genera un JWT válido para el usuario autenticado
      parameters:
      - description: Credenciales de usuario
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/api.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.loginResponse'
        "400":
          description: Solicitud inválida
          schema:
            type: string
        "500":
          description: Error interno
          schema:
            type: string
      summary: Login de usuario
      tags:
      - user
  /api/user/logout:
    post:
      description: Termina la sesión del usuario (simulado)
      responses:
        "200":
          description: Logout exitoso
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Logout del usuario
      tags:
      - user
securityDefinitions:
  BearerAuth:
    description: 'Ingresa el token JWT como: Bearer <token>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
